version: '3.9'

services:
  dev-db: &dev-db
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: yme_monolith
      POSTGRES_PASSWORD: yme_monolith
    ports:
      - 35432:5432
    volumes:
      - devdb:/var/lib/postgresql/data/
  test-db:
    <<: *dev-db
    ports:
      - 35433:5432
    volumes:
      - testdb:/var/lib/postgresql/data/
      
volumes:
  devdb: null
  testdb: null